server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bankDB
  application:
    name: DEBT-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


springdoc:
  api-docs:
    enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
